"""Konfigurasi tunggal untuk pipeline production.

Sebelumnya satu file `config.py` (308 baris, Fase B3 restrukturisasi
memecahnya jadi `paths.py`/`failure.py`/`scrap.py`/`text.py`/`database.py`
per subjek - logic dan nilai TIDAK diubah). Modul ini mengimpor-ulang SEMUA
nama yang dulu diekspor supaya pemanggil yang menulis `from partrisk import
config` lalu memakai `config.X` tidak perlu berubah sama sekali.
"""

from __future__ import annotations

from partrisk.config.database import db_settings
from partrisk.config.failure import (
    AGE_BAND_LABELS,
    AGE_BAND_THRESHOLDS,
    CATBOOST_PARAMS,
    CATEGORICAL_FEATURES,
    DEGRADATION_FEATURES,
    FAILURE_CAPACITY_PER_MONTH,
    FAILURE_HIGH_PROBABILITY_THRESHOLD,
    FAILURE_MEDIUM_PROBABILITY_THRESHOLD,
    FEATURE_COLUMNS,
    FLEET_FEATURES,
    FLEET_WINDOW_DAYS,
    LOW_SUPPORT_LABEL,
    MIN_OBSERVATION_DATE,
    MIN_PART_MODEL_SUPPORT,
    NUMERIC_FEATURES,
    OBSERVATION_STEP_DAYS,
    PREDICTION_HORIZON_DAYS,
    RANDOM_STATE,
    TARGET_HORIZON_DAYS,
    UNKNOWN_LABEL,
)
from partrisk.config.paths import ENV_FILE, FAILURE_MODEL_DIR, MODEL_DIR, PACKAGE_DIR, SCRAP_MODEL_DIR
from partrisk.config.scrap import (
    FAILURE_OUTCOME_STATUS,
    REPAIR_COMPLETED_STATUS,
    SCRAP_CAPACITY_PER_MONTH,
    SCRAP_CATEGORICAL_FEATURES,
    SCRAP_EMBARGO_DAYS,
    SCRAP_ERA_START,
    SCRAP_FEATURE_COLUMNS,
    SCRAP_MEDIUM_CAPACITY_MULTIPLIER,
    SCRAP_MIN_TYPE_SUPPORT,
    SCRAP_MODEL_NAME,
    SCRAP_NUMERIC_FEATURES,
    SCRAP_RANDOM_STATE,
    SCRAP_ROLLING_CUTOFFS,
    SCRAP_STATUS,
    SCRAP_TEST_START,
)
from partrisk.config.text import (
    APPROVED_CLIENT_ALIAS,
    APPROVED_LOCATION_ALIAS,
    FUZZY_MIN_MARGIN,
    FUZZY_MIN_SCORE,
    TEXT_ABBREVIATION_MAPPING,
)

__all__ = [
    "PACKAGE_DIR", "MODEL_DIR", "ENV_FILE", "FAILURE_MODEL_DIR", "SCRAP_MODEL_DIR",
    "CATEGORICAL_FEATURES", "NUMERIC_FEATURES", "FLEET_FEATURES", "FLEET_WINDOW_DAYS",
    "DEGRADATION_FEATURES",
    "FEATURE_COLUMNS", "TARGET_HORIZON_DAYS", "OBSERVATION_STEP_DAYS", "MIN_OBSERVATION_DATE",
    "CATBOOST_PARAMS", "RANDOM_STATE", "MIN_PART_MODEL_SUPPORT", "LOW_SUPPORT_LABEL",
    "UNKNOWN_LABEL", "AGE_BAND_THRESHOLDS", "AGE_BAND_LABELS", "PREDICTION_HORIZON_DAYS",
    "FAILURE_HIGH_PROBABILITY_THRESHOLD", "FAILURE_MEDIUM_PROBABILITY_THRESHOLD",
    "FAILURE_CAPACITY_PER_MONTH",
    "SCRAP_STATUS", "FAILURE_OUTCOME_STATUS", "REPAIR_COMPLETED_STATUS", "SCRAP_ERA_START",
    "SCRAP_EMBARGO_DAYS", "SCRAP_MIN_TYPE_SUPPORT", "SCRAP_CATEGORICAL_FEATURES",
    "SCRAP_NUMERIC_FEATURES", "SCRAP_FEATURE_COLUMNS", "SCRAP_RANDOM_STATE",
    "SCRAP_CAPACITY_PER_MONTH", "SCRAP_MEDIUM_CAPACITY_MULTIPLIER", "SCRAP_TEST_START",
    "SCRAP_ROLLING_CUTOFFS", "SCRAP_MODEL_NAME",
    "APPROVED_LOCATION_ALIAS", "APPROVED_CLIENT_ALIAS", "TEXT_ABBREVIATION_MAPPING",
    "FUZZY_MIN_SCORE", "FUZZY_MIN_MARGIN",
    "db_settings",
]
